server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
 
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: client-service
        uri: http://localhost:8090
        predicates:
        - Path=/clients/**
        filters:
        - RewritePath=/clients/(?<x>.*), /$\{x}
        
      - id: product-service
        uri: http://localhost:8091
        predicates:
        - Path=/products/**
        filters:
        - RewritePath=/products/(?<x>.*), /$\{x}
        
      - id: purchase-service
        uri: http://localhost:8092
        predicates:
        - Path=/purchases/**
        filters:
        - RewritePath=/purchases/(?<x>.*), /$\{x}
        
      - id: transaction-service
        uri: http://localhost:8093
        predicates:
        - Path=/transactions/**
        filters:
        - RewritePath=/transactions/(?<x>.*), /$\{x}
        
      - id: account-service
        uri: http://localhost:8094
        predicates:
        - Path=/accounts/**
        filters:
        - RewritePath=/accounts/(?<x>.*), /$\{x}
        
      - id: withdrawal-service
        uri: http://localhost:8095
        predicates:
        - Path=/withdrawals/**
        filters:
        - RewritePath=/withdrawals/(?<x>.*), /$\{x}
        
      - id: deposit-service
        uri: http://localhost:8096
        predicates:
        - Path=/deposits/**
        filters:
        - RewritePath=/deposits/(?<x>.*), /$\{x}