server:
    port: 8091
  
spring:
  application:
    name: product-service
  data:
    mongodb:
      database: db_product
      uri: mongodb://localhost:27017/product

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - java.net.ConnectException
    instances:
      productServiceCircuitBreaker:
        baseConfig: default
